### ISSUE TITLE
unable to import functions filter_shap and get_rank_df

### ISSUE THREAD

**Issue by mttbzz** [Wong718/CNN-for-transcriptome#1]
Dear Mr./Mrs,

I am using your script for tissua transcriptomic analysis, and I am stuck in the second script when I import shap package.
I am using python 3.10 and correctly imported shap, but apparently shap.utils does not have filter_shap and get_rank_df functions. I tried different shap versions (from 0.36 to more recent ones) but the same problem occurs.
Could you tell me if these functions where deprecated and how to replace them?

Thanks

Bests
Matteo Bozzoli

**Comment by Wong718** [comment]
Dear Mr./Mrs,

Thank you for your questions, so that we found that some of the python scripts were not uploaded to github in time. At present, these scripts have been uploaded, including filter_shap and get_rank_df functions that you mentioned in issue. 

Thank you.

Bests
Zijie Wang
